source = hyprland/monitors.conf

source = hyprland/workspaces.conf

source = hyprland/exec.conf

source = hyprland/variables.conf

source = hyprland/look.conf 

source = hyprland/input.conf 

source = hyprland/binds.conf

source = hyprland/windowrules.conf
