# for gui apps to be able to ask password to get elevated acces
exec-once = systemctl --user start hyprpolkitagent

# bar
exec-once = quickshell

# wallpaper 
exec-once = hyprpaper

# idler 
exec-once = hypridle 
